#!/usr/bin/env python3
print("🚀 Starting Ansys Workbench Scripting MCP Server")
print("=" * 60)
print(f"Server URL: http://127.0.0.1:8001")
print(f"SSE Endpoint: http://127.0.0.1:8001/sse")
print("")
print("🔧 Ansys Workbench Scripting Server Capabilities:")
print("  📄 9 Resources:")
print("    • ansys://workbench/overview - Workbench automation overview")
print("    • ansys://pymechanical/architecture - PyMechanical implementation details")
print("    • ansys://python/cpython-vs-ironpython - Python implementation comparison")
print("    • ansys://reference/quick-guide - Quick reference for common tasks")
print("    • ansys://act/development - ACT development guide")
print("    • ansys://dpf/post-processing - DPF post-processing reference")
print("    • ansys://scripting/examples - Comprehensive scripting examples")
print("    • ansys://api/reference - API reference documentation")
print("")
print("  🛠️  3 Tools:")
print("    • search_ansys_docs - Search across 2000+ pages of documentation")
print("    • get_code_example - Find code examples for specific topics")
print("    • get_chapter_content - Extract specific chapters from PDF manuals")
print("")
print("  🎯 3 Prompts:")
print("    • generate_ansys_script - Generate automation scripts")
print("    • debug_ansys_error - Diagnose and resolve scripting errors")
print("    • convert_ironpython_to_cpython - Migrate legacy scripts")
print("")
print("🎯 Purpose: Augment AI assistants with comprehensive Ansys Workbench scripting knowledge")
print("📚 Documentation: 40+ MB extracted from 2042 pages across 4 Ansys manuals + HTML docs")
print("🔍 Search: Full-text search across all documentation with relevance scoring")
print("")
print("Connect MCP Inspector to: http://127.0.0.1:8001/sse")
print("Press Ctrl+C to stop the server")
print("=" * 60)